### ISSUE TITLE
Pivot: When Pivot item content is scrollable, scrollbar gets clipped

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1094]
### Repro Steps

1. Go to the [Pivot sample](http://try.buildwinjs.com/#pivot:create) on the Try Site.
2. In the `CSS` of the sample, delete this style which hides the issue:

  ```css
  .win-pivot-item .win-pivot-item-content {
    padding: 0 0 0 12px;
  }
  ```

3. Run the sample.

Notice that the scrollbar gets clipped:

![screen shot 2015-04-29 at 3 58 37 pm](https://cloud.githubusercontent.com/assets/199935/7403253/c2c9edf0-ee88-11e4-903d-735a60a93eae.png)

### Fix

We should delete the WinJS style that sets `win-pivot-item-content`'s width to `calc(100% - 28px)`. By default, a div sizes to its parent's width.
