### ISSUE TITLE
SplitView: The pane does not scroll

### ISSUE THREAD

**Issue by jseanxu** [winjs/winjs#1097]
The pane usually houses a list of toggles/buttons and is likely to overflow - it should scroll vertically by default.

**Comment by bradboose** [comment]
Hello--

I am running into this issue now.  I can navigate up and down a list via keyboard controls, but can't scroll inside the splitView's content area.  You mention 'by default' - is a there a property I can set to get to work?

Thanks

**Comment by rigdern** [comment]
@bradboose This bug is about making the pane scroll. Are you interested in making the pane or the content area scroll? Either way, the fix is about styling the [CSS `overflow` property](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow) on the correct element.

If you want the pane to scroll vertically, you'd do something like:

```css
#app .win-splitview-pane {
  overflow-y: auto;
}
```

And you want the content area to scroll vertically, you'd do something like:

```css
#app .win-splitview-content {
  overflow-y: auto;
}
```

Note that I included an ID in the selector (`#app`) to ensure that the rule has enough specificity to beat the SplitView's default `overflow` style.
