### ISSUE TITLE
4.01 release has improper minified css flex attributes

### ISSUE THREAD

**Issue by obeliskos** [winjs/winjs#1274]
I believe the minification process you are using to minify ui-dark.css and ui-light.css is improperly stripping out a % symbol from the flex attributes here (and possibly other locations) : 
```css
.win-splitview .win-splitview-contentwrapper {
  position: relative;
  z-index: 0;
  -ms-flex: 1 1 0%;
  -webkit-flex: 1 1 0%;
  flex: 1 1 0%;
  overflow: hidden;
}
```
When using the minified files, the applied flex styles are rendered as 1 1 0 (without percent) rendering the content pane invisible.
