### ISSUE TITLE
Custom icons - Best approach?

### ISSUE THREAD

**Issue by sondreb** [winjs/winjs#1286]
What is the best approach to start adding custom icons to a WinJS 4.0 based app? It would be nice to be able to actually simply load another font or SVG files and have them rendered by setting the icon name same as the native icons. There is not even a sign in/sign out icon in the AppBarIcon enumeration. Is this the only list of icons that exists in Symbols.ttf?

https://msdn.microsoft.com/en-us/library/windows/apps/hh770557.aspx

**Comment by jayrenn** [comment]
Hi @sondreb! I think the best way to add custom icons would be to use the `extraClass` property.

For instance:
```javascript
var command = new WinJS.UI.AppBarCommand(null, {label: 'sign in', extraClass: 'signincommand'});
```
```css
button.win-disposable.win-command.signincommand .win-commandimage:before {
    font-family: Custom Font;
    content: "\E0AE"; /* e.g. the Unicode value of the desired icon from the custom font */ 
}
```

Let me know if that fulfills your scenario!
