### ISSUE TITLE
NavBarCommand has no visual feedback on focus

### ISSUE THREAD

**Issue by unindented** [winjs/winjs#1329]
You explicitly remove `outline` from `NavBarCommand`, but you don't provide any alternative visual feedback, which makes it impossible to know what's currently focused:

```css
.win-navbarcommand-button:focus {
    z-index: 1;
    outline: none;
}
```

**Comment by unindented** [comment]
An easy fix could be to apply `hover` styles to `focus` too:

```css
html.win-hoverable .win-navbarcommand-button:hover,
html.win-hoverable .win-navbarcommand-button:focus,
html.win-hoverable .win-navbarcommand-splitbutton:hover,
html.win-hoverable .win-navbarcommand-splitbutton:focus {
    background-color: rgba(0, 0, 0, 0.19);
}
```
