### ISSUE TITLE
AppBar: Secondary section command's icon is ignored

### ISSUE THREAD

**Issue by vajnorcan** [winjs/winjs#1476]
I'm trying to show the phone icon for the command that would immediately call the traffic incident reporting info line, but it seems like the app bar ignored this for any type of the command that is placed in the overflow area. thanks! great job btw

**Comment by jdalton** [comment]
Hi @vajnorcan!

You can address this with CSS :D

```css
button[aria-label="Thing"] .win-menucommand-liner span.win-label:before {
  content: "Icon unicode here";
}
```
