### ISSUE TITLE
WinJS 4.4.0 Pivot: Slow population of PivotItem

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1502]
I pre-load all my data during app start asynchronously. The app is very responsive during startup.
However, when I switch to a PivotItem that contains a listview that should display the data, it takes several seconds before the listview shows any items. Also the touch on the pivot header does not feel very responsive at all.
The old Pivot performed better I think (and looked much more gorgeous too)

```html
<div class="garages" data-win-control="WinJS.UI.PivotItem" data-win-options="{ header: 'Parkäuser' }">
            <div class="garage-item-template" data-win-control="WinJS.Binding.Template">
                <div class="garage-item" data-win-bind="this['status']:status WinJS.Binding.setAttribute">
                    <h2 class="name" data-win-bind="textContent: name"></h2>
                    <div class="store-count" data-win-bind="this['count']:nearby_store_count WinJS.Binding.setAttribute"><div data-win-bind="textContent:nearby_store_count"></div></div>
                </div>
            </div>
            <div data-win-control="WinJS.UI.ListView"
                 data-win-options="{
                    itemDataSource: App.Model.garages.dataSource,
                    itemTemplate:select('.garage-item-template'),
                    layout: {type: WinJS.UI.ListLayout, orientation: 'vertical'}}">
            </div>
        </div>
```

```css
.garage-item {
    display: -ms-grid;
    -ms-grid-columns: 1fr 30px;
    grid-columns: 1fr 30px;
    -ms-grid-rows: 1fr;
    border-bottom: 1px solid gray;
}

.garage-item .store-count {
    -ms-grid-column:2;
    background:url("../images/retailer-icon.png") no-repeat;
    width:26px;
    height:30px;
    position:relative;
    margin: auto;
}

.garage-item[status=upcoming],
.garage-item .store-count[count='0'],
.dealer-item[status=closed] {
    opacity:0.4;
}

.garage-item .store-count > div {
    text-align:center;
    position:absolute;
    bottom: 2px;
    width: 100%;
    font-weight: bold;
}
```
