### ISSUE TITLE
ListView: win-surface element isn't sizing properly in Chrome + Firefox

### ISSUE THREAD

**Issue by jumyhre** [winjs/winjs#156]
Create a horizontal ungrouped ListView, and include this CSS on the page:

``` css
        .win-surface {
            border: 3px solid green;
        }
```

In IE, the win-surface element expands to fit the content, so that green border'll go all the way to the scroll end. In Firefox and Chrome, the win-surface element only expands to fit the viewport bounds, and items run past the win-surface bounds.

This bug affects the ListView's SemanticZoom implementation, which clamps the zoom location to be within the bounds of the win-surface element, and also breaks anyone styling the win-surface element with a background, etc.
