### ISSUE TITLE
AutoSuggestBox suggestion list displays incorrect when using bootstrap

### ISSUE THREAD

**Issue by NCC1701M** [winjs/winjs#1568]
Bootstrap is using 

```css
*{
      box-sizing: border-box;
}
```

but this doesn't display the list of suggestion correct. The items are compressed and overlay each other. Please fix this by reset the box-sizing property for the AutoSuggestBox
