### ISSUE TITLE
Firefox intrinsic controls have default css that needs to be overwritten

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#163]
I discovered this while debugging a failing unit test in AppBar (#117)

The width of the button was 10 pixels too wide, but adding this to the CSS styles fixes that test.

``` CSS
<style type="text/css">
        button::-moz-focus-inner {
          padding: 0px;
          border: 0px;
        }
</style>
```

It would appear that we might have more CSS failures in firefox that we may not have tests for.
http://stackoverflow.com/questions/5459893/how-to-reset-default-button-style-in-firefox-4
