### ISSUE TITLE
Incorrect or missing definitions for controls disabled state

### ISSUE THREAD

**Issue by avandgard** [winjs/winjs#1647]
The only definition of disabled state I've found, is the following -ms-high-contrast definition, with to me weird color definition 'GrayText'. 

```css
@media (-ms-high-contrast) {
  ...
  .win-textbox:disabled,
  .win-textarea:disabled {
    border-color: GrayText;
    color: GrayText;
  }
  ...
}
```

Is this meant as a feature (missing definitions) or it is in kind of "incomplete" or "TODO" state? Should I w8 (or contribute) or handle it myself?

In general, does this project support (or going to) forms, especially complex forms? So far I have not found much form components (calendar, date/time picker, range, spinner, combined inputs, formated inputs ...).
