### ISSUE TITLE
ListView: panning experience is not good on iOS

### ISSUE THREAD

**Issue by banguero** [winjs/winjs#205]
From previous prototypes, to get inertia, we need to add:

``` css
.win-listview .win-viewport { -webkit-overflow-scrolling: touch; }
```

When we were debugging a Cordova app, we also noticed very few scroll events, which we might be able to mitigate with this:

http://stackoverflow.com/questions/8546863/current-scroll-position-when-using-webkit-overflow-scrollingtouch-safari-ios
