### ISSUE TITLE
Pivot headers need more font-family fallbacks

### ISSUE THREAD

**Issue by banguero** [winjs/winjs#358]
Currently it has:

``` css
 button.win-pivot-header,
    button.win-pivot-header:hover,
    button.win-pivot-header:hover:active {
        background-color: transparent;
        border: 0;
        margin: 0;
        padding: 0px 9px;
        letter-spacing: 0px;
        min-height: 0;
        min-width: 0;
        font-size: 45pt;
        font-weight: 400;
        font-family: "Segoe WP Semilight", "Segoe";
    }
```

When you try it in a Cordova app in iOS, other text in the page (e.g. ListView items see console log below), but the pivot headers don't look good:

![image](https://cloud.githubusercontent.com/assets/1873511/3459492/40ce574a-020d-11e4-8c1d-2a68035cc85b.png)
