### ISSUE TITLE
ListView hover outline should be reconsidered

### ISSUE THREAD

**Issue by banguero** [winjs/winjs#497]
We currently add a 3px outline to items on hover:

```css
.win-listview .win-container:hover {
    outline: 3px solid rgba(255, 255, 255, 0.3);
}
```

![image](https://cloud.githubusercontent.com/assets/1873511/3846224/b19444c6-1e5a-11e4-9ebe-effd7f410761.png)

This does not look well in IE when zoom is not 100%, e.g 150%:

![image](https://cloud.githubusercontent.com/assets/1873511/3846204/88e8be58-1e5a-11e4-80f1-527a7cfee787.png)

Notice how it looks like an inset:

![image](https://cloud.githubusercontent.com/assets/1873511/3846236/e672377a-1e5a-11e4-84c4-ce1588b1e3d0.png)

There are also cases in which the item content provided by the app, could be affected by the outline, e.g. see #472 

Opening this bug to track what we should so about this... Should we just continue changing the items background color on hover, but not add a 3px outline?
