### ISSUE TITLE
Flash when tapping items in webkit 

### ISSUE THREAD

**Issue by banguero** [winjs/winjs#521]
We noticed that in the Stocks Cordova app there was a flash when tapping appbar buttons, or listview items  and got around the issue by adding:

``` css
body {
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}
```

We should add that style to the WinJS stylesheet.

That is the equivalent of having `<meta name="msapplication-tap-highlight" content="no" />` in Windows.
