### ISSUE TITLE
Searchbox suggestion flyout is not using the correct font fallback outside of Windows

### ISSUE THREAD

**Issue by banguero** [winjs/winjs#548]
Cordova iOS app:
![image](https://cloud.githubusercontent.com/assets/1873511/3987035/7c9fa462-28a1-11e4-8db9-b3cbe927c09e.png)

These 3 rules should specify a font-family, and let out defaults fallbacks handle it:

``` css
.win-searchbox-suggestion-result {
    #flex > .display-flex();
    padding: 0 18px;
    height: 60px;
    font-family: "Segoe UI";
    font-size: 11pt;
    outline: none;
}

.win-searchbox-suggestion-query {
    padding: 9px 18px 11px 18px;
    font-family: "Segoe UI";
    font-weight: normal;
    outline: none;
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
    font-size: 11pt;
    line-height: 20px;
}

.win-searchbox-suggestion-separator {
    #flex > .display-flex();
    padding: 0 18px;
    height: 40px;
    font-family: "Segoe UI";
    font-size: 11pt;
}
```

PS: I searched the rest of the codebase for other instances of this, and searchbox is the only control that was still doing this.
