### ISSUE TITLE
Remove z-index: -1's from styles to improve animation perf

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#788]
`z-index: -1` prevents an element from being independently animated in IE. We should remove usages of it from our styles.

Current usages:
```css
.win-contentdialog .win-contentdialog-backgroundoverlay {
  z-index: -1;
}

button[aria-checked=true].win-command::after {
  z-index: -1;
}

.win-menu button.win-command-flyout-activated::after, .win-menu button.win-command-flyout-activated::after {
  z-index: -1;
}

.win-menu button.win-command-flyout-activated::after {
  z-index: -1;
}

.win-ui-dark button[aria-checked=true].win-command::after {
  z-index: -1;
}

.win-ui-dark.win-menu button.win-command-flyout-activated::after, .win-ui-dark .win-menu button.win-command-flyout-activated::after {
  z-index: -1;
}

.win-ui-dark .win-menu button.win-command-flyout-activated::after {
  z-index: -1;
}

button[aria-checked=true].win-command::after {
  z-index: -1;
}

.win-menu button.win-command-flyout-activated::after, .win-menu button.win-command-flyout-activated::after {
  z-index: -1;
}

.win-menu button.win-command-flyout-activated::after {
  z-index: -1;
}
```
