### ISSUE TITLE
SplitView: Pane width can't be full screen on iOS

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#946]
### Impact

There's no way clean way to make the pane's width full screen on iOS. This could be a common desire in mobile scenarios. For example, the SplitView on the mobile Try Site is configured like this (screenshot looks good because it's in Chrome):
![image](https://cloud.githubusercontent.com/assets/199935/6404751/79a06df4-bdd0-11e4-8c9e-11e0f268f18f.png)

### Repro Steps

1. Download and unzip repro.zip from http://1drv.ms/1armyTU
2. Open repro\index.html on an iOS device (I reproed it on a physical iPhone (no emulator))

**Expected result:** The pane (green) is the same width as the screen

**Actual result:** The pane (green) is only as wide as its content.

### Details

The page attempts to set the size of the pane to be the width of the screen using `100vw`:

```css
/* Doesn't work on iOS (due to an iOS bug?) */
#app .win-splitview-pane {
  width: 100vw;
}
```

This works on all browsers I've tested except mobile Safari on iOS.

An alternate approach would be to set the width of the pane to match the width of the SplitView (`100%`):

```css
/* Doesn't work in any browser */
#app .win-splitview-pane {
  width: 100%;
}
```

However, this doesn't work anywhere because the `pane`'s parent is `panewrapper` which is restricting the width of the `pane`. A workaround is to also set the width of the `panewrapper`:

```css
/* Works everywhere but styles private CSS class panewrapper */
#app .win-splitview-panewrapper,
#app .win-splitview-pane {
  width: 100%;
}
```

This solution works everywhere but it requires styling `win-splitview-panewrapper` which is a private CSS class.

None of these solutions is ideal. If this use case is important, how can we change the SplitView to make it easy for developers to achieve this scenario? Or is there a solution I'm missing that easily enables this scenario without changing the SplitView?
