### ISSUE TITLE
AppBarCommands are too wide in Firefox

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#955]
Commands are 68px wide in IE, Chrome and Safari. However in Firefox it is 74px because border and padding are being applied to the `button::-moz-focus-inner` pseudo element. 

This difference in widths between browsers means that developers cannot safely size the width of their Toolbar to fit exactly 3 commands in the action area, and have it work correctly in all browsers.

The fix is to apply the following CSS to our `button.win-command` rule.

```CSS
   ::-moz-focus-inner {
        padding: 0;
        border: 0;
    }
```
Separators and content commands do not have this affliction.
